%YAML 1.2
---

# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
# To stop the grid and cleanup the created containers, run docker-compose down
version: "3"

services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - grid
  
  chrome:
    image: selenium/node-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - grid

  firfox:
    image: selenium/node-firefox-debug
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5901:5900"
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - grid

networks:
  grid:
